"""empty message

Revision ID: 19a2aa024ce0
Revises: c1e572060155
Create Date: 2022-05-27 12:46:32.357712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a2aa024ce0'
down_revision = 'c1e572060155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miss', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('word_count')
        batch_op.drop_column('miss')

    # ### end Alembic commands ###
