"""empty message

Revision ID: 9863d7e95042
Revises: 6012343e745e
Create Date: 2022-05-27 18:58:37.671125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9863d7e95042'
down_revision = '6012343e745e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_quiz')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=True))
        batch_op.drop_constraint('fk_quiz_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('username')

    op.create_table('_alembic_tmp_quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('miss', sa.INTEGER(), nullable=True),
    sa.Column('word_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
