"""empty message

Revision ID: cc169c24f6ba
Revises: 41c86da8b4ed
Create Date: 2022-05-27 13:26:38.254407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc169c24f6ba'
down_revision = '41c86da8b4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=False))
        batch_op.drop_constraint('fk_quiz_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
