"""empty message

Revision ID: fb100ccc6f00
Revises: 471d0b6f970b
Create Date: 2022-05-27 18:56:07.249771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb100ccc6f00'
down_revision = '471d0b6f970b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_quiz')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=True))
        batch_op.alter_column('miss',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('word_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_quiz_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('word_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('miss',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('username')

    op.create_table('_alembic_tmp_quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('miss', sa.INTEGER(), nullable=False),
    sa.Column('word_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
